### ISSUE TITLE
USB HID Terminal

### ISSUE THREAD

**Issue by kerpz** [rayshobby/hid-serial#1]
Hi ray I think you used a different protocol.
I tried this app and it didn't work

https://github.com/452/USBHIDTerminal

regards,
kerpz

**Comment by rayshobby** [comment]
I am not aware of any 'standard' protocol of USB HID. It's all customized. The HID Serial implemented here has a 8 byte report buffer for outgoing data and 32 byte report buffer for incoming data. Not sure what's the data format of the USBHIDTerminal you pointed to, but since both are open-source, you can modify either to make them compatible.
